### ISSUE TITLE
Interrupt script

### ISSUE THREAD

**Issue by rmccorm4** [alpacahq/example-hft#2]
Hi,

I haven't tried to run this yet, but just something I noticed in the README:

It mentions stopping the script with a `CTRL-Z` interrupt, but wouldn't that just continue the process in the background? Did you mean `CTRL-C`?

Again, haven't even tried to run it, just an observation that could be very dangerous if correct in this context.

Thanks,
Ryan

**Comment by ttt733** [comment]
Ctrl+Z (SIGTSTP) does not allow the process to execute in the background. It just leaves it alive, but stopped, not executing. The reason I recommended Ctrl+Z is that sometimes, depending on where in the execution you catch it, you may have to press Ctrl+C twice to kill the program. (It leads to process buildup, but I figured that was preferable to someone getting confused about how to stop execution.) But if this is a point of confusion anyhow, I'll go ahead and change it with a note that you may need to press the interrupt a couple times.
